M48
; DRILL file {KiCad 8.0.7} date 2024-12-30T22:20:31-0800
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-12-30T22:20:31-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.800
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.750
%
G90
G05
T1
X-8.83Y-9.25
X-8.83Y-20.73
T2
X3.5Y-3.5
X3.5Y-26.5
X61.5Y-3.5
X61.5Y-26.5
M30
